server {
    listen 80;
    server_name ruleviewer.local;

    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/xml;
    gzip_min_length 1024;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
