// ============================================================
// devMock.ts
// 開發用假資料
//
// 設計原則：
//   每筆 VALUES 只做一件事：用判斷式決定一個變數的值
//   COLUMN1 = 被設定的變數名稱
//   VALUE   = 決定該變數值的單一運算式（可含 IF/ELSE）
//
// 結構：
//   DEV       → __DEV_主副線範例__（主副線視覺測試）
//   APF_CHECK → APF_LOT_VALIDATOR, APF_RECIPE_CHECK, APF_LOT_SCHEDULER
//   APF_FORMAT→ APF_NORMALIZER,    APF_FIELD_MAPPER,  APF_RECIPE_BUILDER
// ============================================================

import type { RuleData } from "./types";

// ── DEV Phase（主副線視覺測試） ───────────────────────────────
export const DEV_MOCK_PHASE     = "DEV";
export const DEV_MOCK_RULE_NAME = "__DEV_主副線範例__";

export const DEV_MOCK_RULES: RuleData[] = [
  {
    PHASE: "DEV", RULE_NAME: DEV_MOCK_RULE_NAME,
    BLOCK_NAME: "START",      BLOCK_TYPE: "START",    BLOCK_GROUP: "G1", BLOCK_SEQ: "1",
    KEY: null, POSX: 300, POSY: 100, PRE_BLOCK: null, VALUES: [],
  },
  {
    PHASE: "DEV", RULE_NAME: DEV_MOCK_RULE_NAME,
    BLOCK_NAME: "DECISION",   BLOCK_TYPE: "DECISION", BLOCK_GROUP: "G1", BLOCK_SEQ: "2",
    KEY: "COLUMN", POSX: 300, POSY: 250, PRE_BLOCK: ["START"],
    VALUES: [
      { COLUMN1: "RESULT", COLUMN2: "COLUMN", VALUE: 'IF COLUMN = "A" THEN "TRUE" ELSE "FALSE"' },
    ],
  },
  {
    PHASE: "DEV", RULE_NAME: DEV_MOCK_RULE_NAME,
    BLOCK_NAME: "TRUE_PATH",  BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "G1", BLOCK_SEQ: "3",
    KEY: null, POSX: 150, POSY: 420, PRE_BLOCK: ["DECISION"],
    VALUES: [
      { COLUMN1: "STATUS", COLUMN2: null, VALUE: '/* 條件成立 */ "PASS"' },
    ],
  },
  {
    PHASE: "DEV", RULE_NAME: DEV_MOCK_RULE_NAME,
    BLOCK_NAME: "FALSE_PATH", BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "G1", BLOCK_SEQ: "4",
    KEY: null, POSX: 450, POSY: 420, PRE_BLOCK: ["DECISION"],
    VALUES: [
      { COLUMN1: "STATUS", COLUMN2: null, VALUE: '/* 條件不成立 */ "SKIP"' },
    ],
  },
  {
    PHASE: "DEV", RULE_NAME: DEV_MOCK_RULE_NAME,
    BLOCK_NAME: "MERGE",      BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "G1", BLOCK_SEQ: "5",
    KEY: null, POSX: 300, POSY: 600,
    PRE_BLOCK: ["TRUE_PATH", "FALSE_PATH"], // [0]=主線 [1]=副線
    VALUES: [
      { COLUMN1: "MERGE_RESULT", COLUMN2: "STATUS", VALUE: 'MergeResult("TRUE_PATH", "FALSE_PATH")' },
    ],
  },
  {
    PHASE: "DEV", RULE_NAME: DEV_MOCK_RULE_NAME,
    BLOCK_NAME: "END",        BLOCK_TYPE: "END",      BLOCK_GROUP: "G1", BLOCK_SEQ: "6",
    KEY: null, POSX: 300, POSY: 760, PRE_BLOCK: ["MERGE"], VALUES: [],
  },
];

// ── APF Phase 定義 ────────────────────────────────────────────
export const MOCK_PHASES = ["APF_CHECK", "APF_FORMAT"] as const;
export type MockPhase = typeof MOCK_PHASES[number];

export const MOCK_RULES_BY_PHASE: Record<MockPhase, string[]> = {
  APF_CHECK:  ["APF_LOT_VALIDATOR", "APF_RECIPE_CHECK",  "APF_LOT_SCHEDULER"],
  APF_FORMAT: ["APF_NORMALIZER",    "APF_FIELD_MAPPER",  "APF_RECIPE_BUILDER"],
};

// ── APF_CHECK / APF_LOT_VALIDATOR ────────────────────────────
//   START → CHECK_LOT_FORMAT → LOT_VALID   ─(主)→ MERGE_VAL → LOG_RESULT → END
//                            ↘ LOT_INVALID ─(副)↗
const APF_LOT_VALIDATOR: RuleData[] = [
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_VALIDATOR",
    BLOCK_NAME: "START_LOT_VAL",    BLOCK_TYPE: "START",    BLOCK_GROUP: "VALIDATE", BLOCK_SEQ: "1",
    KEY: null, POSX: 300, POSY: 50, PRE_BLOCK: null, VALUES: [],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_VALIDATOR",
    BLOCK_NAME: "CHECK_LOT_FORMAT", BLOCK_TYPE: "DECISION", BLOCK_GROUP: "VALIDATE", BLOCK_SEQ: "2",
    KEY: "LOT_ID", POSX: 300, POSY: 200, PRE_BLOCK: ["START_LOT_VAL"],
    VALUES: [
      { COLUMN1: "LOT_FORMAT_STATUS", COLUMN2: "LOT_ID",
        VALUE: 'IF LOT_ID = "" THEN "EMPTY"\nELSE IF ValidateLotFormat(LOT_ID) = "FAIL" THEN "INVALID"\nELSE "OK"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_VALIDATOR",
    BLOCK_NAME: "LOT_VALID",        BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "VALIDATE", BLOCK_SEQ: "3",
    KEY: null, POSX: 130, POSY: 390, PRE_BLOCK: ["CHECK_LOT_FORMAT"],
    VALUES: [
      { COLUMN1: "LOT_STATUS", COLUMN2: null,      VALUE: '"VALID"' },
      { COLUMN1: "LOG_MSG",    COLUMN2: "LOT_ID",  VALUE: 'ConcatMsg("LOT_FORMAT_OK", LOT_ID)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_VALIDATOR",
    BLOCK_NAME: "LOT_INVALID",      BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "VALIDATE", BLOCK_SEQ: "4",
    KEY: null, POSX: 470, POSY: 390, PRE_BLOCK: ["CHECK_LOT_FORMAT"],
    VALUES: [
      { COLUMN1: "LOT_STATUS", COLUMN2: null,       VALUE: '"INVALID"' },
      { COLUMN1: "ERR_MSG",    COLUMN2: "ERR_CODE", VALUE: 'FormatErr("LOT_FORMAT_ERR", LOT_ID, ERR_CODE)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_VALIDATOR",
    BLOCK_NAME: "MERGE_VAL",        BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "VALIDATE", BLOCK_SEQ: "5",
    KEY: null, POSX: 300, POSY: 570,
    PRE_BLOCK: ["LOT_VALID", "LOT_INVALID"], // [0]=主線 [1]=副線
    VALUES: [
      { COLUMN1: "MERGE_STATUS", COLUMN2: "LOT_STATUS", VALUE: 'MergeValidation(LOT_STATUS, ERR_CODE)' },
      { COLUMN1: "NOTIFY_FLAG",  COLUMN2: "LOT_STATUS", VALUE: 'IF LOT_STATUS = "INVALID" THEN "Y" ELSE "N"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_VALIDATOR",
    BLOCK_NAME: "LOG_RESULT",       BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "VALIDATE", BLOCK_SEQ: "6",
    KEY: null, POSX: 300, POSY: 730, PRE_BLOCK: ["MERGE_VAL"],
    VALUES: [
      { COLUMN1: "LOG_LEVEL",  COLUMN2: "LOT_STATUS", VALUE: 'IF LOT_STATUS = "VALID" THEN "PASS" ELSE "FAIL"' },
      { COLUMN1: "LOG_DETAIL", COLUMN2: "LOT_STATUS", VALUE: 'IF LOT_STATUS = "VALID" THEN LOT_ID ELSE ConcatStr(LOT_ID, ERR_CODE)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_VALIDATOR",
    BLOCK_NAME: "END_LOT_VAL",      BLOCK_TYPE: "END",      BLOCK_GROUP: "VALIDATE", BLOCK_SEQ: "7",
    KEY: null, POSX: 300, POSY: 890, PRE_BLOCK: ["LOG_RESULT"], VALUES: [],
  },
];

// ── APF_CHECK / APF_RECIPE_CHECK ─────────────────────────────
//   START → GET_RECIPE_VER → CHECK_VER_VALID → APPLY_RECIPE   ─(主)→ MERGE_RECIPE → END
//                                            ↘ DEFAULT_RECIPE ─(副)↗
const APF_RECIPE_CHECK: RuleData[] = [
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_RECIPE_CHECK",
    BLOCK_NAME: "START_RCP_CHK",   BLOCK_TYPE: "START",    BLOCK_GROUP: "RECIPE", BLOCK_SEQ: "1",
    KEY: null, POSX: 300, POSY: 50, PRE_BLOCK: null, VALUES: [],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_RECIPE_CHECK",
    BLOCK_NAME: "GET_RECIPE_VER",  BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "RECIPE", BLOCK_SEQ: "2",
    KEY: "RECIPE_NAME", POSX: 300, POSY: 200, PRE_BLOCK: ["START_RCP_CHK"],
    VALUES: [
      { COLUMN1: "$ChamberID",   COLUMN2: "EQUIP_CODE",  VALUE: 'GetChamber(EQUIP_CODE)' },
      { COLUMN1: "$RecipeParam", COLUMN2: "RECIPE_NAME", VALUE: 'FetchParam($ChamberID, RECIPE_NAME)' },
      { COLUMN1: "RECIPE_VER",   COLUMN2: "RECIPE_NAME", VALUE: 'GetRecipeVersion(RECIPE_NAME, EQUIP_CODE)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_RECIPE_CHECK",
    BLOCK_NAME: "CHECK_VER_VALID", BLOCK_TYPE: "DECISION", BLOCK_GROUP: "RECIPE", BLOCK_SEQ: "3",
    KEY: "RECIPE_VER", POSX: 300, POSY: 370, PRE_BLOCK: ["GET_RECIPE_VER"],
    VALUES: [
      { COLUMN1: "VER_STATUS", COLUMN2: "RECIPE_VER",
        VALUE: 'IF RECIPE_VER = "" OR RECIPE_VER = "N/A" THEN "USE_DEFAULT"\nELSE IF CheckRecipeExpiry(RECIPE_VER) = "EXPIRED" THEN "USE_DEFAULT"\nELSE "APPLY_LATEST"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_RECIPE_CHECK",
    BLOCK_NAME: "APPLY_RECIPE",    BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "RECIPE", BLOCK_SEQ: "4",
    KEY: null, POSX: 140, POSY: 560, PRE_BLOCK: ["CHECK_VER_VALID"],
    VALUES: [
      { COLUMN1: "APPLY_STATUS", COLUMN2: "RECIPE_VER",  VALUE: 'ApplyRecipe(RECIPE_NAME, RECIPE_VER)' },
      { COLUMN1: "EQUIP_PARAM",  COLUMN2: "$ChamberID",  VALUE: 'SetEquipParam($ChamberID, $RecipeParam)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_RECIPE_CHECK",
    BLOCK_NAME: "DEFAULT_RECIPE",  BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "RECIPE", BLOCK_SEQ: "5",
    KEY: null, POSX: 460, POSY: 560, PRE_BLOCK: ["CHECK_VER_VALID"],
    VALUES: [
      { COLUMN1: "APPLY_STATUS", COLUMN2: "EQUIP_CODE", VALUE: 'ApplyDefaultRecipe(EQUIP_CODE)' },
      { COLUMN1: "WARN_MSG",     COLUMN2: null,          VALUE: 'FormatWarn("RECIPE_VER_MISSING", EQUIP_CODE)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_RECIPE_CHECK",
    BLOCK_NAME: "MERGE_RECIPE",    BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "RECIPE", BLOCK_SEQ: "6",
    KEY: null, POSX: 300, POSY: 740,
    PRE_BLOCK: ["APPLY_RECIPE", "DEFAULT_RECIPE"], // [0]=主線 [1]=副線
    VALUES: [
      { COLUMN1: "VERIFY_STATUS", COLUMN2: "EQUIP_CODE",  VALUE: 'VerifyRecipeApplied(EQUIP_CODE)' },
      { COLUMN1: "ALERT_FLAG",    COLUMN2: "APPLY_STATUS", VALUE: 'IF APPLY_STATUS = "FAIL" THEN "Y" ELSE "N"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_RECIPE_CHECK",
    BLOCK_NAME: "END_RCP_CHK",     BLOCK_TYPE: "END",      BLOCK_GROUP: "RECIPE", BLOCK_SEQ: "7",
    KEY: null, POSX: 300, POSY: 900, PRE_BLOCK: ["MERGE_RECIPE"], VALUES: [],
  },
];

// ── APF_CHECK / APF_LOT_SCHEDULER ────────────────────────────
// 變數傳遞鏈：$Station/$QueueDepth → MAX_WAIT → SCHEDULE_TIME → ASSIGN_FLAG
//
//   START → GET_LOT_INFO →  ASSESS_PRIORITY →
//             → HIGH_PRI_PATH ─(主)→ MERGE_SCHED → UPDATE_SCHEDULE → END
//             → NORM_PRI_PATH ─(副)↗
const APF_LOT_SCHEDULER: RuleData[] = [
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "START_SCHED",     BLOCK_TYPE: "START",    BLOCK_GROUP: "SCHED", BLOCK_SEQ: "1",
    KEY: null, POSX: 300, POSY: 50, PRE_BLOCK: null, VALUES: [],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "GET_LOT_INFO",    BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "SCHED", BLOCK_SEQ: "2",
    KEY: "LOT_ID", POSX: 300, POSY: 200, PRE_BLOCK: ["START_SCHED"],
    VALUES: [
      { COLUMN1: "$Station",     COLUMN2: "EQUIP_CODE", VALUE: 'GetStation(EQUIP_CODE)' },
      { COLUMN1: "$QueueDepth",  COLUMN2: "$Station",   VALUE: 'GetQueueDepth($Station)' },
      { COLUMN1: "LOT_GRADE",    COLUMN2: "LOT_ID",     VALUE: 'GetLotGrade(LOT_ID)' },
      { COLUMN1: "EQUIP_STATUS", COLUMN2: "EQUIP_CODE", VALUE: 'GetEquipStatus(EQUIP_CODE)' },
      { COLUMN1: "MAX_WAIT",     COLUMN2: "LOT_GRADE",  VALUE: 'GetMaxWait(LOT_GRADE, $QueueDepth)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "ASSESS_PRIORITY", BLOCK_TYPE: "DECISION", BLOCK_GROUP: "SCHED", BLOCK_SEQ: "3",
    KEY: "LOT_GRADE", POSX: 300, POSY: 370, PRE_BLOCK: ["GET_LOT_INFO"],
    VALUES: [
      { COLUMN1: "PRIORITY_PATH", COLUMN2: "LOT_GRADE",
        VALUE: 'IF LOT_GRADE = "A" AND EQUIP_STATUS = "IDLE" THEN "HIGH"\nELSE IF LOT_GRADE = "A" OR LOT_GRADE = "B" THEN "NORMAL"\nELSE "LOW"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "HIGH_PRI_PATH",   BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "SCHED", BLOCK_SEQ: "4",
    KEY: null, POSX: 120, POSY: 560, PRE_BLOCK: ["ASSESS_PRIORITY"],
    VALUES: [
      { COLUMN1: "PRIORITY",      COLUMN2: null,         VALUE: '"HIGH"' },
      { COLUMN1: "SCHEDULE_TIME", COLUMN2: null,         VALUE: '"IMMEDIATE"' },
      { COLUMN1: "ASSIGN_FLAG",   COLUMN2: null,         VALUE: '"Y"' },
      { COLUMN1: "URGENT_FLAG",   COLUMN2: "LOT_GRADE",  VALUE: 'FlagUrgent(LOT_ID, LOT_GRADE)' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "NORM_PRI_PATH",   BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "SCHED", BLOCK_SEQ: "5",
    KEY: null, POSX: 480, POSY: 560, PRE_BLOCK: ["ASSESS_PRIORITY"],
    VALUES: [
      { COLUMN1: "PRIORITY",      COLUMN2: "LOT_GRADE",   VALUE: 'IF LOT_GRADE = "B" THEN "NORMAL" ELSE "LOW"' },
      { COLUMN1: "SCHEDULE_TIME", COLUMN2: "$Station",    VALUE: 'CalcNextSlot($Station, MAX_WAIT)' },
      { COLUMN1: "$TargetSlot",   COLUMN2: "$QueueDepth", VALUE: 'ResolveSlot($Station, $QueueDepth)' },
      { COLUMN1: "ASSIGN_FLAG",   COLUMN2: "$TargetSlot", VALUE: 'IF $TargetSlot != "" THEN "Y" ELSE "N"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "MERGE_SCHED",     BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "SCHED", BLOCK_SEQ: "6",
    KEY: null, POSX: 300, POSY: 760,
    PRE_BLOCK: ["HIGH_PRI_PATH", "NORM_PRI_PATH"], // [0]=主線 [1]=副線
    VALUES: [
      { COLUMN1: "MERGE_RESULT",  COLUMN2: "SCHEDULE_TIME", VALUE: 'MergeSchedule(LOT_ID, SCHEDULE_TIME, ASSIGN_FLAG)' },
      { COLUMN1: "EQUIP_RESERVE", COLUMN2: "ASSIGN_FLAG",   VALUE: 'IF ASSIGN_FLAG = "Y" THEN ReserveEquip(EQUIP_CODE, SCHEDULE_TIME) ELSE "SKIP"' },
      { COLUMN1: "NOTIFY_FLAG",   COLUMN2: "PRIORITY",      VALUE: 'IF PRIORITY = "HIGH" THEN "Y" ELSE "N"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "UPDATE_SCHEDULE", BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "SCHED", BLOCK_SEQ: "7",
    KEY: null, POSX: 300, POSY: 940, PRE_BLOCK: ["MERGE_SCHED"],
    VALUES: [
      { COLUMN1: "WRITE_STATUS", COLUMN2: "SCHEDULE_TIME", VALUE: 'WriteSchedule(LOT_ID, EQUIP_CODE, SCHEDULE_TIME, PRIORITY)' },
      { COLUMN1: "ALERT_FLAG",   COLUMN2: "LOT_GRADE",     VALUE: 'IF LOT_GRADE = "A" AND ASSIGN_FLAG = "N" THEN "Y" ELSE "N"' },
    ],
  },
  {
    PHASE: "APF_CHECK", RULE_NAME: "APF_LOT_SCHEDULER",
    BLOCK_NAME: "END_SCHED",       BLOCK_TYPE: "END",      BLOCK_GROUP: "SCHED", BLOCK_SEQ: "8",
    KEY: null, POSX: 300, POSY: 1100, PRE_BLOCK: ["UPDATE_SCHEDULE"], VALUES: [],
  },
];

// ── APF_FORMAT / APF_NORMALIZER ───────────────────────────────
//   START → READ_RAW_DATA → NORM_LOT_INFO   ─(主)→ BUILD_APF_OUTPUT → END
//                         ↘ NORM_RECIPE_INFO─(副)↗
const APF_NORMALIZER: RuleData[] = [
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_NORMALIZER",
    BLOCK_NAME: "START_NORM",         BLOCK_TYPE: "START",   BLOCK_GROUP: "NORM", BLOCK_SEQ: "1",
    KEY: null, POSX: 300, POSY: 50, PRE_BLOCK: null, VALUES: [],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_NORMALIZER",
    BLOCK_NAME: "READ_RAW_DATA",      BLOCK_TYPE: "PROCESS", BLOCK_GROUP: "NORM", BLOCK_SEQ: "2",
    KEY: "SOURCE_PATH", POSX: 300, POSY: 200, PRE_BLOCK: ["START_NORM"],
    VALUES: [
      { COLUMN1: "RAW_DATA",    COLUMN2: "SOURCE_PATH", VALUE: 'ReadAPFRawData(SOURCE_PATH)' },
      { COLUMN1: "FILE_STATUS", COLUMN2: "FILE_SIZE",   VALUE: 'IF FILE_SIZE = 0 THEN "EMPTY" ELSE "OK"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_NORMALIZER",
    BLOCK_NAME: "NORM_LOT_INFO",      BLOCK_TYPE: "PROCESS", BLOCK_GROUP: "NORM", BLOCK_SEQ: "3",
    KEY: null, POSX: 130, POSY: 390, PRE_BLOCK: ["READ_RAW_DATA"],
    VALUES: [
      { COLUMN1: "LOT_ID",    COLUMN2: null, VALUE: 'NormalizeLotId(LOT_ID)' },
      { COLUMN1: "PHASE",     COLUMN2: null, VALUE: 'NormalizePhase(PHASE)' },
      { COLUMN1: "NORM_FLAG", COLUMN2: null, VALUE: '"Y"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_NORMALIZER",
    BLOCK_NAME: "NORM_RECIPE_INFO",   BLOCK_TYPE: "PROCESS", BLOCK_GROUP: "NORM", BLOCK_SEQ: "4",
    KEY: null, POSX: 470, POSY: 390, PRE_BLOCK: ["READ_RAW_DATA"],
    VALUES: [
      { COLUMN1: "RECIPE_NAME", COLUMN2: null,          VALUE: 'NormalizeRecipeName(RECIPE_NAME)' },
      { COLUMN1: "RECIPE_VER",  COLUMN2: null,          VALUE: 'MapRecipeVersion(RECIPE_VER)' },
      { COLUMN1: "RECIPE_NAME", COLUMN2: "RECIPE_NAME", VALUE: 'IF RECIPE_NAME = "" THEN "UNKNOWN" ELSE RECIPE_NAME' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_NORMALIZER",
    BLOCK_NAME: "BUILD_APF_OUTPUT",   BLOCK_TYPE: "PROCESS", BLOCK_GROUP: "NORM", BLOCK_SEQ: "5",
    KEY: null, POSX: 300, POSY: 570,
    PRE_BLOCK: ["NORM_LOT_INFO", "NORM_RECIPE_INFO"], // [0]=主線 [1]=副線
    VALUES: [
      { COLUMN1: "APF_PAYLOAD",  COLUMN2: "LOT_ID",       VALUE: 'BuildAPFOutput(LOT_ID, RECIPE_NAME, PHASE)' },
      { COLUMN1: "BUILD_STATUS", COLUMN2: "APF_PAYLOAD",  VALUE: 'IF APF_PAYLOAD = "" THEN "FAIL" ELSE "OK"' },
      { COLUMN1: "WRITE_RESULT", COLUMN2: "BUILD_STATUS", VALUE: 'IF BUILD_STATUS = "OK" THEN WriteOutput(OUTPUT_PATH) ELSE "SKIP"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_NORMALIZER",
    BLOCK_NAME: "END_NORM",           BLOCK_TYPE: "END",     BLOCK_GROUP: "NORM", BLOCK_SEQ: "6",
    KEY: null, POSX: 300, POSY: 730, PRE_BLOCK: ["BUILD_APF_OUTPUT"], VALUES: [],
  },
];

// ── APF_FORMAT / APF_FIELD_MAPPER ────────────────────────────
//   START → MAP_EQUIP_CODE → MAP_STEP_CODE → VALIDATE_MAPPING → EXPORT_MAPPING → END
const APF_FIELD_MAPPER: RuleData[] = [
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_FIELD_MAPPER",
    BLOCK_NAME: "START_MAP",         BLOCK_TYPE: "START",    BLOCK_GROUP: "MAP", BLOCK_SEQ: "1",
    KEY: null, POSX: 300, POSY: 50, PRE_BLOCK: null, VALUES: [],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_FIELD_MAPPER",
    BLOCK_NAME: "MAP_EQUIP_CODE",    BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "MAP", BLOCK_SEQ: "2",
    KEY: "EQUIP_ID", POSX: 300, POSY: 200, PRE_BLOCK: ["START_MAP"],
    VALUES: [
      { COLUMN1: "EQUIP_CODE", COLUMN2: "EQUIP_TYPE",
        VALUE: 'IF EQUIP_TYPE = "ETC" THEN MapETCCode(EQUIP_ID)\nELSE IF EQUIP_TYPE = "CVD" THEN MapCVDCode(EQUIP_ID)\nELSE MapDefaultCode(EQUIP_ID)' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_FIELD_MAPPER",
    BLOCK_NAME: "MAP_STEP_CODE",     BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "MAP", BLOCK_SEQ: "3",
    KEY: "STEP_ID", POSX: 300, POSY: 370, PRE_BLOCK: ["MAP_EQUIP_CODE"],
    VALUES: [
      { COLUMN1: "STEP_CODE",     COLUMN2: "STEP_ID",    VALUE: 'MapStepCode(STEP_ID, PHASE)' },
      { COLUMN1: "MAPPING_VALID", COLUMN2: "STEP_CODE",  VALUE: 'ValidateStepMapping(STEP_CODE, EQUIP_CODE)' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_FIELD_MAPPER",
    BLOCK_NAME: "VALIDATE_MAPPING",  BLOCK_TYPE: "DECISION", BLOCK_GROUP: "MAP", BLOCK_SEQ: "4",
    KEY: null, POSX: 300, POSY: 530, PRE_BLOCK: ["MAP_STEP_CODE"],
    VALUES: [
      { COLUMN1: "MAPPING_STATUS", COLUMN2: "EQUIP_CODE",
        VALUE: 'IF EQUIP_CODE = "" OR STEP_CODE = "" THEN "MAPPING_FAIL"\nELSE IF CheckMappingConsistency(EQUIP_CODE, STEP_CODE) = "FAIL" THEN "INCONSISTENT"\nELSE "OK"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_FIELD_MAPPER",
    BLOCK_NAME: "EXPORT_MAPPING",    BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "MAP", BLOCK_SEQ: "5",
    KEY: null, POSX: 300, POSY: 700, PRE_BLOCK: ["VALIDATE_MAPPING"],
    VALUES: [
      { COLUMN1: "EXPORT_EQUIP",  COLUMN2: "EQUIP_CODE",    VALUE: 'WriteAPFField("EQUIP", EQUIP_CODE)' },
      { COLUMN1: "EXPORT_STEP",   COLUMN2: "STEP_CODE",     VALUE: 'WriteAPFField("STEP", STEP_CODE)' },
      { COLUMN1: "EXPORT_STATUS", COLUMN2: "OUTPUT_FORMAT", VALUE: 'ExportMapping(EQUIP_CODE, STEP_CODE, OUTPUT_FORMAT)' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_FIELD_MAPPER",
    BLOCK_NAME: "END_MAP",           BLOCK_TYPE: "END",      BLOCK_GROUP: "MAP", BLOCK_SEQ: "6",
    KEY: null, POSX: 300, POSY: 860, PRE_BLOCK: ["EXPORT_MAPPING"], VALUES: [],
  },
];

// ── APF_FORMAT / APF_RECIPE_BUILDER ──────────────────────────
// 變數傳遞鏈：$BaseParam/$SchemaVer → BASE_RECIPE →
//             LOT_SPEC_OVERRIDE / EQUIP_SPEC_OVERRIDE → FINAL_RECIPE
//
//   START → LOAD_BASE_RECIPE →
//             → PATCH_LOT_SPEC   ─(主)→ ASSEMBLE_RECIPE → VALIDATE_RECIPE → COMMIT_RECIPE → END
//             → PATCH_EQUIP_SPEC ─(副)↗
const APF_RECIPE_BUILDER: RuleData[] = [
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "START_BUILD",        BLOCK_TYPE: "START",    BLOCK_GROUP: "BUILD", BLOCK_SEQ: "1",
    KEY: null, POSX: 300, POSY: 50, PRE_BLOCK: null, VALUES: [],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "LOAD_BASE_RECIPE",   BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "BUILD", BLOCK_SEQ: "2",
    KEY: "RECIPE_NAME", POSX: 300, POSY: 210, PRE_BLOCK: ["START_BUILD"],
    VALUES: [
      { COLUMN1: "$BaseParam",  COLUMN2: "EQUIP_CODE",  VALUE: 'LoadParamSet(EQUIP_CODE)' },
      { COLUMN1: "$SchemaVer",  COLUMN2: "RECIPE_NAME", VALUE: 'GetSchema(RECIPE_NAME)' },
      { COLUMN1: "BASE_RECIPE", COLUMN2: "RECIPE_NAME", VALUE: 'LoadBaseRecipe(RECIPE_NAME, $SchemaVer)' },
      { COLUMN1: "RECIPE_VER",  COLUMN2: "EQUIP_CODE",  VALUE: 'GetRecipeVersion(RECIPE_NAME, EQUIP_CODE)' },
      { COLUMN1: "EQUIP_PARAM", COLUMN2: "$BaseParam",  VALUE: 'NormalizeParam($BaseParam)' },
      { COLUMN1: "LOT_GRADE",   COLUMN2: "LOT_ID",      VALUE: 'GetLotGrade(LOT_ID)' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "PATCH_LOT_SPEC",     BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "BUILD", BLOCK_SEQ: "3",
    KEY: null, POSX: 110, POSY: 400, PRE_BLOCK: ["LOAD_BASE_RECIPE"],
    VALUES: [
      { COLUMN1: "LOT_SPEC_OVERRIDE", COLUMN2: "LOT_GRADE",
        VALUE: 'IF LOT_GRADE = "A" THEN BuildAGradeSpec(BASE_RECIPE, RECIPE_VER) ELSE BuildStdSpec(BASE_RECIPE)' },
      { COLUMN1: "SPEC_LOG",          COLUMN2: "LOT_GRADE",
        VALUE: 'IF LOT_GRADE = "A" THEN LogSpec("HIGH_GRADE_SPEC", LOT_SPEC_OVERRIDE) ELSE "SKIP"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "PATCH_EQUIP_SPEC",   BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "BUILD", BLOCK_SEQ: "4",
    KEY: null, POSX: 490, POSY: 400, PRE_BLOCK: ["LOAD_BASE_RECIPE"],
    VALUES: [
      { COLUMN1: "EQUIP_SPEC_OVERRIDE", COLUMN2: "EQUIP_PARAM",
        VALUE: 'BuildEquipSpec(BASE_RECIPE, EQUIP_PARAM, RECIPE_VER)' },
      { COLUMN1: "EQUIP_SPEC_OVERRIDE", COLUMN2: null,
        VALUE: 'IF EQUIP_SPEC_OVERRIDE = "" THEN BASE_RECIPE ELSE EQUIP_SPEC_OVERRIDE' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "ASSEMBLE_RECIPE",    BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "BUILD", BLOCK_SEQ: "5",
    KEY: null, POSX: 300, POSY: 600,
    PRE_BLOCK: ["PATCH_LOT_SPEC", "PATCH_EQUIP_SPEC"], // [0]=主線 [1]=副線
    VALUES: [
      { COLUMN1: "FINAL_RECIPE",   COLUMN2: "BASE_RECIPE",
        VALUE: 'MergeSpec(BASE_RECIPE, LOT_SPEC_OVERRIDE, EQUIP_SPEC_OVERRIDE)' },
      { COLUMN1: "ASSEMBLE_STATUS", COLUMN2: "FINAL_RECIPE",
        VALUE: 'IF FINAL_RECIPE = "" THEN "FAIL" ELSE "OK"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "VALIDATE_RECIPE",    BLOCK_TYPE: "DECISION", BLOCK_GROUP: "BUILD", BLOCK_SEQ: "6",
    KEY: "FINAL_RECIPE", POSX: 300, POSY: 780, PRE_BLOCK: ["ASSEMBLE_RECIPE"],
    VALUES: [
      { COLUMN1: "RECIPE_STATUS", COLUMN2: "FINAL_RECIPE",
        VALUE: 'IF FINAL_RECIPE = "" THEN "EMPTY"\nELSE IF ValidateRecipe(FINAL_RECIPE, EQUIP_CODE) = "FAIL" THEN "INVALID"\nELSE IF CheckParamRange(FINAL_RECIPE) = "OUT" THEN "OUT_OF_RANGE"\nELSE "OK"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "COMMIT_RECIPE",      BLOCK_TYPE: "PROCESS",  BLOCK_GROUP: "BUILD", BLOCK_SEQ: "7",
    KEY: null, POSX: 300, POSY: 960, PRE_BLOCK: ["VALIDATE_RECIPE"],
    VALUES: [
      { COLUMN1: "COMMIT_STATUS", COLUMN2: "FINAL_RECIPE", VALUE: 'CommitRecipe(FINAL_RECIPE, EQUIP_CODE)' },
      { COLUMN1: "APF_RECIPE",    COLUMN2: null,            VALUE: 'WriteAPFField("RECIPE", FINAL_RECIPE)' },
      { COLUMN1: "AUDIT_LOG",     COLUMN2: "LOT_GRADE",
        VALUE: 'IF LOT_GRADE = "A" THEN AuditLog("A_GRADE_RECIPE", FINAL_RECIPE, LOT_ID) ELSE "SKIP"' },
    ],
  },
  {
    PHASE: "APF_FORMAT", RULE_NAME: "APF_RECIPE_BUILDER",
    BLOCK_NAME: "END_BUILD",          BLOCK_TYPE: "END",      BLOCK_GROUP: "BUILD", BLOCK_SEQ: "8",
    KEY: null, POSX: 300, POSY: 1120, PRE_BLOCK: ["COMMIT_RECIPE"], VALUES: [],
  },
];

// ── 統一查詢入口 ──────────────────────────────────────────────
export const MOCK_RULE_DATA: Record<string, RuleData[]> = {
  "APF_LOT_VALIDATOR":  APF_LOT_VALIDATOR,
  "APF_RECIPE_CHECK":   APF_RECIPE_CHECK,
  "APF_LOT_SCHEDULER":  APF_LOT_SCHEDULER,
  "APF_NORMALIZER":     APF_NORMALIZER,
  "APF_FIELD_MAPPER":   APF_FIELD_MAPPER,
  "APF_RECIPE_BUILDER": APF_RECIPE_BUILDER,
};
